Lock during the entire build.
So that we don't interleave the various parts of various builds.

diff --git a/bin/tinbuild b/bin/tinbuild
--- a/bin/tinbuild
+++ b/bin/tinbuild
@@ -40,7 +40,7 @@ done
 # at the same time, just one of them builds / installs / whatever at the given
 # time
 if which flock > /dev/null 2>&1 ; then
-	LOCK="flock -x /tmp/tinbuild-lockfile"
+	LOCK=1
 fi
 
 ## subroutines
@@ -62,6 +62,12 @@ usage ()
 	echo "-p <pass>  SMTP password for auth login"
 	echo "-t <name>  send tinderbox mails, identify self as <name>"
 	echo "-w <N>     specify timeout in secs between subsequent pull requests"
+}
+
+# echo the message to the screen including a timestamp
+echots ()
+{
+	echo "[`date -u '+%Y-%m-%d %H:%M:%S'`]" "$@"
 }
 
 getCommitters ()
@@ -86,7 +92,7 @@ sendMailMsg ()
 	fi
 	eval $CMD
 
-	echo "Sent a mail to \"$TO\" with subject \"$SUBJECT\"."
+	echots "Sent a mail to \"$TO\" with subject \"$SUBJECT\"."
 }
 
 reportError ()
@@ -268,18 +274,35 @@ while true; do
 
 	# try to build
 	build_status="build_failed"
-	if ! $LOCK $NICE ./autogen.sh ${DISTRO_CONFIG:+ --with-distro=${DISTRO_CONFIG}} >autogen.log 2>&1 ; then
-		reportError committer "$rough_checkout_date" `printf "autogen.sh / configure failed - error is:\n\n"` "$(cat autogen.log)"
-	elif ! $LOCK $NICE $MAKE clean >clean.log 2>&1 ; then
-		reportError committer "$rough_checkout_date" `printf "cleaning up failed - error is:\n\n"` "$(tail -n100 clean.log)"
-	elif ! $LOCK $NICE $MAKE >build.log 2>&1 ; then
-		reportError committer "$rough_checkout_date" `printf "building failed - error is:\n\n"` "$(tail -n100 build.log)"
-#	elif ! $LOCK $NICE make smoketest > smoketest.log 2>&1 ; then
-#		reportError committer "$rough_checkout_date" `printf "smoketest failed - error is:\n\n"` "$(tail -n100 smoketest.log)"
-	elif ( test "`uname | cut -c 1-6`" != "CYGWIN" ) && ! $LOCK $NICE $MAKE dev-install >install.log 2>&1 ; then
-		reportError committer "$rough_checkout_date" `printf "dev installation failed - error is:\n\n"` "$(tail -n100 install.log)"
-	else
-		echo "Build done - checkout from $rough_checkout_date successful."
+	(
+		if [ "$LOCK" = "1" ] ; then
+			flock -x 200
+		fi
+
+		retval=0
+
+		if ! $NICE ./autogen.sh ${DISTRO_CONFIG:+ --with-distro=${DISTRO_CONFIG}} >autogen.log 2>&1 ; then
+			reportError committer "$rough_checkout_date" `printf "autogen.sh / configure failed - error is:\n\n"` "$(cat autogen.log)"
+			retval=1
+		elif ! $NICE $MAKE clean >clean.log 2>&1 ; then
+			reportError committer "$rough_checkout_date" `printf "cleaning up failed - error is:\n\n"` "$(tail -n100 clean.log)"
+			retval=1
+		elif ! $NICE $MAKE >build.log 2>&1 ; then
+			reportError committer "$rough_checkout_date" `printf "building failed - error is:\n\n"` "$(tail -n100 build.log)"
+			retval=1
+#		elif ! $NICE make smoketest > smoketest.log 2>&1 ; then
+#			reportError committer "$rough_checkout_date" `printf "smoketest failed - error is:\n\n"` "$(tail -n100 smoketest.log)"
+#			retval=1
+		elif ( test "`uname | cut -c 1-6`" != "CYGWIN" ) && ! $NICE $MAKE dev-install >install.log 2>&1 ; then
+			reportError committer "$rough_checkout_date" `printf "dev installation failed - error is:\n\n"` "$(tail -n100 install.log)"
+			retval=1
+		fi
+
+		exit $retval
+	) 200>/tmp/tinbuild-lockfile
+
+	if [ "$?" = "0" ] ; then
+		echots "Build done - checkout from $rough_checkout_date successful."
 		gitHeads > prev-git-heads.txt
 
 		prev_success=$last_success
@@ -306,7 +329,7 @@ while true; do
 		mv $I prev-$I 2>/dev/null
 	done
 
-	echo "Waiting $PAUSE_SECONDS seconds."
+	echots "Waiting $PAUSE_SECONDS seconds."
 	sleep $PAUSE_SECONDS
 
 	# new commits?
@@ -318,7 +341,7 @@ while true; do
 		new_head=$(gitHeads)
 
 		if test "$old_head" != "$new_head"; then
-			echo "Repo updated, going to build"
+			echots "Repo updated, going to build"
 			break
 		fi
 
