tab/space cosmetic fixup

diff --git a/bin/tinbuild2 b/bin/tinbuild2
--- a/bin/tinbuild2
+++ b/bin/tinbuild2
@@ -239,186 +239,186 @@ while [ "${1}" != "" ]; do
     arg=${1#*=}
     has_arg=
     if [ "${1}" != "${parm?}" ] ; then
-	has_arg=1
+        has_arg=1
     else
-	arg=""
+        arg=""
     fi
 #    echo "parm=!${parm}!"
 #    echo "arg=!${arg}!"
     case "${parm}" in
         -0)  # avoid calling *_clean functions (incremental build)
-	    DO_NOT_CLEAN=1
-	    ;;
+            DO_NOT_CLEAN=1
+            ;;
         -a)  # email to the branch's author for out-of-tinderbox branch buildbot
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		BRANCH_AUTHOR="$arg"
-	    fi
-	    ;;
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                BRANCH_AUTHOR="$arg"
+            fi
+            ;;
         -b)  # to override the branch name to use
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		BRANCH="$arg"
-	    fi
-	    ;;
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                BRANCH="$arg"
+            fi
+            ;;
         -c)  # whether to invoke the sanity-check function
-	    sanity_check # do not return
-	    ;;
+            sanity_check # do not return
+            ;;
         -d)  # wrap make in a watchdog
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		WATCHDOG="makewatchdog $arg -- "
-	    fi
-	    ;;
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                WATCHDOG="makewatchdog $arg -- "
+            fi
+            ;;
         -e)  # whether to use flock to protect the build-cycle
-	    LOCK=0
-	    ;;
+            LOCK=0
+            ;;
         -f)  # whether to force an initial rebuild on restart, even if the pull-info are unchanged
-	    FORCE_REBUILD=1
-	    ;;
+            FORCE_REBUILD=1
+            ;;
         -g)  # gerit's ref to fetch. This imply a one time build, no memory
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		GERRIT_REF="${arg}"
-		BRANCH="gerrit"
-		SEND_MAIL="none"
-		mode="gerrit-patch"
-	    fi
-	    ;;
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                GERRIT_REF="${arg}"
+                BRANCH="gerrit"
+                SEND_MAIL="none"
+                MODE="gerrit-patch"
+            fi
+            ;;
         -h)  # display help
-	    usage;
-	    exit
-	    ;;
+            usage;
+            exit
+            ;;
         -i)  # be gentle on i/o
-	    NICE="$NICE ionice -c3"
-	    ;;
+            NICE="$NICE ionice -c3"
+            ;;
         -k)  # do not override the local autogen.lastrun if present
-	    KEEP_AUTOGEN="YES"
-	    ;;
+            KEEP_AUTOGEN="YES"
+            ;;
         -m)  # which email to wend and to whom
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		SEND_MAIL="${arg}"
-	    fi
-	    ;;
-	--mode)
-	    # operating mode of the tinbuild
-	    # tb,prime,gerrit,tb-gerrit,gerrit-tb
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		MODE="${arg}"
-	    fi
-	    ;;
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                SEND_MAIL="${arg}"
+            fi
+            ;;
+        --mode)
+            # operating mode of the tinbuild
+            # tb,prime,gerrit,tb-gerrit,gerrit-tb
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                MODE="${arg}"
+            fi
+            ;;
         -n)  # build 'nicely' :-)
-	    NICE="$NICE nice"
-	    ;;
+            NICE="$NICE nice"
+            ;;
         -p)  # profile to use to deterine extra parameter (email mostly) and autogen arguments
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		PROFILE_NAME="${arg}"
-	    fi
-	    ;;
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                PROFILE_NAME="${arg}"
+            fi
+            ;;
         -r)  # whether to upload daily build.
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		PUSH_NIGHTLIES=1
-		BANDWIDTH="${arg}"
-	    fi
-	    ;;
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                PUSH_NIGHTLIES=1
+                BANDWIDTH="${arg}"
+            fi
+            ;;
         -s)  # where to stage the build in case of -z with upload
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		STAGE_DIR="${arg}"
-	    fi
-	    ;;
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                STAGE_DIR="${arg}"
+            fi
+            ;;
         -t)  # whether to run tests after the build
-	    DO_TESTS=1
-	    ;;
+            DO_TESTS=1
+            ;;
         -v)  # print more messages
-	    V=1
-	    ;;
+            V=1
+            ;;
         -w)  # cool-down time after a build, in seconds
-	    if [ -z "${has_arg}" ] ; then
-		shift;
-		arg="$1"
-	    fi
-	    if [ -z "${arg}" ] ; then
-		echo "Missing argument for option $parm" 1>&2
-		exit -1
-	    else
-		PAUSE_SECONDS="${arg}"
-	    fi
-	    ;;
+            if [ -z "${has_arg}" ] ; then
+                shift;
+                arg="$1"
+            fi
+            if [ -z "${arg}" ] ; then
+                echo "Missing argument for option $parm" 1>&2
+                exit -1
+            else
+                PAUSE_SECONDS="${arg}"
+            fi
+            ;;
         -x)  # Push builds to bibisect repo (per buildbot and major version)
-	    PUSH_TO_BIBISECT_REPO=1
-	    ;;
+            PUSH_TO_BIBISECT_REPO=1
+            ;;
         -z)
             # to run an initial build (without sending any email) to establish a 'baseline'
-	    MODE="prime"
-	    ;;
+            MODE="prime"
+            ;;
         -*)
-	    echo "Invalid option $1" 1>&2
-	    usage;
-	    exit -1
-	    ;;
-	*)
-	    echo "Invalid argument $1" 1>&2
+            echo "Invalid option $1" 1>&2
+            usage;
             exit -1
-	    ;;
+            ;;
+        *)
+            echo "Invalid argument $1" 1>&2
+            exit -1
+            ;;
     esac
     shift
 done
@@ -524,32 +524,31 @@ fi
 
 case "${MODE?}" in
     prime)
-	if [ "$SEND_MAIL" != "owner" ] ; then
+	    if [ "$SEND_MAIL" != "owner" ] ; then
             SEND_MAIL=""  # we don't want to notify the tinderbox
-	fi
-	if [ "$PUSH_NIGHTLIES" = "1" ] ; then
+	    fi
+	    if [ "$PUSH_NIGHTLIES" = "1" ] ; then
             rm -f "${METADATA_DIR?}/tb_${B?}_last-upload-day.txt"
-	fi
-	run_primer
-	;;
+	    fi
+	    run_primer
+	    ;;
     tb)
-	run_tb_loop
-	;;
+	    run_tb_loop
+	    ;;
     gerrit)
-	run_gerrit_loop
-	;;
+	    run_gerrit_loop
+	    ;;
     tb-gerrit)
-	run_tb_gerrit_loop "tb"
-	;;
+	    run_tb_gerrit_loop "tb"
+	    ;;
     gerrit-tb)
-	run_tb_gerrit_loop "gerrit"
-	;;
+	    run_tb_gerrit_loop "gerrit"
+	    ;;
     fair)
-	run_tb_gerrit_loop "fair"
-	;;
-
+	    run_tb_gerrit_loop "fair"
+	    ;;
     gerrit-patch)
-	run_gerrit_patch
-	;;
+	    run_gerrit_patch
+	    ;;
 esac
 
