tinbuild2: make sure that ARTIFACTDIR is set-up and is a git repo

diff --git a/bin/tinbuild2 b/bin/tinbuild2
--- a/bin/tinbuild2
+++ b/bin/tinbuild2
@@ -9,8 +9,8 @@ BIN_DIR=$(dirname "$0")
 PAUSE_SECONDS=$((15*60))
 PUSH_NIGHTLIES=0
 PUSH_TO_BIBISECT_REPO=0
+ARTIFACTDIR=
 BUILDDIR=`pwd`
-ARTIFACTDIR="${BUILDDIR}/../bibisect-repository"
 BUILDCOMMIT=
 SEND_MAIL="all"
 LOCK=1
@@ -270,6 +270,17 @@ if [ ! -d ${METADATA_DIR} ] ; then
     mkdir -p "${METADATA_DIR?}" || exit 1
 fi
 
+if [ "${PUSH_TO_BIBISECT_REPO}" != "0" ] ; then
+    if  [ -z "${ARTIFACTDIR}" ] ; then
+	echo "Error: to do bibisect you must define ARTIFACTDIR to point to your bibisect git repo" 1>&2
+	rc=1
+    else
+	if [ ! -d "${ARTIFACTDIR}" -o ! -d "${ARTIFACTDIR}/.git" ] ; then
+	    echo "Error: ARTIFACTDIR:${ARTIFACTDIR} is not a git repositor" 1>&2
+	    rc=1
+	fi
+    fi
+fi
 # if we want email to be sent, we must make sure that the required parameters are set in the profile (or in the environment)
 case "$SEND_MAIL" in
     all|tb|owner|debug|author)
